services:
  worker:
    platform: linux/amd64
    build:
      context: .
    command: ["./run.sh",  "run_all"]
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
#    deploy:
#      resources:
#        limits:
#          memory: 10g
